name: Deploy API

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Create maven settings.xml
      uses: s4u/maven-settings-action@v2.4.0
      with:
        servers: '[{ "id": "nexus", "username": "${{ secrets.MAVEN_USER }}", "password": "${{ secrets.MAVEN_PASSWORD }}" }]'
    - name: Publish to Imprex Nexus
      run: mvn -Daether.connector.basic.threads=1 -s ~/.m2/settings.xml deploy -pl orebfuscator-api