name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: BuildTools cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository/org/spigotmc
        key: ${{ runner.os }}-maven-${{ secrets.CACHE_VERSION }}-${{ hashFiles('./.github/workflows/buildtools.sh') }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ secrets.CACHE_VERSION }}-
    - name: BuildTools Java 8
      run: |
        sh ./.github/workflows/buildtools.sh java-8
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: BuildTools Java 16
      run: |
        sh ./.github/workflows/buildtools.sh java-16
    - name: Build
      run: |
        mvn clean package -pl orebfuscator-plugin -B --also-make -Drevision=$RELEASE_VERSION
        mkdir dist
        mv orebfuscator-plugin/target/orebfuscator-*.jar ./dist
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*"
        name: Release ${{ env.RELEASE_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
